project:
  type: website

website:
  title: "Formula 1 - Analyze to Action"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: proposal.qmd
        text: Proposal

format:
  html:
    theme:  
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

execute:
  freeze: auto
  
editor: visual

